Module4 api
IuriiSokolov/TicketingSystem pull request #2
Opened 2024-10-15 10:35 UTC by IuriiSokolov

2024-10-18 08:00 UTC, olegbaslak requested changes

2024-10-18 08:00 UTC, olegbaslak commented on TicketingSystem.ApiService/Endpoints/EventEndpoints.cs
> +        private async Task<Ok<List<TicketsFromEventAndSectionDto>>> GetSeatsOfSectionOfEvent(int event_id, int section_id, IEventRepository repo)
Generally, naming convention is `eventId`, not snake case. Not for fix, just keep in mind that normally C# devs would expect certain naming rules and inconsistency produces questions like "why was it done this way"

2024-10-18 08:00 UTC, olegbaslak commented on TicketingSystem.ApiService/Repositories/EventRepository/EventRepository.cs
> +            var result = (from sec in _context.Sections
Avoid using query language at all costs, use extensions and IQueryable methods instead. Query language is very cumbersome and much harder to support due to lack of reusability and possibilities for code parts extraction.

2024-10-18 08:00 UTC, olegbaslak commented on TicketingSystem.ApiService/Repositories/EventRepository/EventRepository.cs
> +            var result = (from sec in _context.Sections
I didn't check but it should be similar to smth like

```csharp
var result = await _context.Tickets
                .Where(t => t.EventId == eventId && t.Seat.SectionId == sectionId)
                .Select(t => new TicketsFromEventAndSectionDto
                {
                    SectionId = t.Seat.SectionId,
                    RowNumber = t.Seat.RowNumber,
                    SeatId = t.SeatId,
                    SeatStatus = t.Status,
                    PriceCategoryId = t.PriceCategoryId,
                    PriceCategoryName = t.PriceCategory.PriceCategoryName
                })
                .ToListAsync();
```

2024-10-18 08:00 UTC, olegbaslak commented on TicketingSystem.ApiService/Repositories/CartRepository/CartRepository.cs
> +        public async Task<(Cart?, float TotalPriceUsd)> AddTicketToCartAsync(Guid cartId, int eventId, int seatId)
Let's separate DAL and BLL. Repositories should not contain any business logic. Also, it makes sense to encapsulate service return result into DTOs.

When returning entities you do not know what navigation properties should be included, with DTO, the intention is clear. Also in this case DTO would contain `TotalPriceUsd` instead of using tuples (which is harder to maintain and update when used in many places).

In BLL you can also perform input validation and DTO mapping.

2024-10-18 08:00 UTC, olegbaslak commented on TicketingSystem.ApiService/Repositories/CartRepository/CartRepository.cs
> +            if (ticket == null)
Not need to be used here, just a tip for your future projects. Take a look at how errors could be handled with functional approach and `Result<>` type: https://www.milanjovanovic.tech/blog/functional-error-handling-in-dotnet-with-the-result-pattern.

One of the top advantages are:
- clear state of what to expect from the method
- execution speed compared to exception handling (e.g., you'll later have more cases then just NotFound), especially when error happens

Disadvantages:
- lack of support from language perspective (Though there's a proposal now in discussion for DIs, so in future there should be support from C# perspective for such types)
- error handling may seem too verbose, since it requires to explicitly handle each error (or pass it further)

2024-10-18 08:00 UTC, olegbaslak commented on TicketingSystem.ApiService/Repositories/CartRepository/CartRepository.cs
> +        public async Task<(Cart?, float TotalPriceUsd)> AddTicketToCartAsync(Guid cartId, int eventId, int seatId)
Also (not in this program too), if you want to make your code more complex in favor of reusability and clear intentions, you can try to use Specification pattern https://medium.com/@cizu64/the-query-specification-pattern-in-ddd-net-core-25f1ec580f32 or simply just accepting `Expression` in your repository generic methods. This could also be done in some `BaseRepository<TEntity>` with smth like 
```csharp
public async Task<TEntity> GetFirstOrDefaultAsync(Expression<Func<TEntity, bool>> predicate)
        {
            return await _context.Set<TEntity>().FirstOrDefaultAsync(predicate: predicate);
        }
```

2024-10-20 15:48 UTC, IuriiSokolov commented on TicketingSystem.ApiService/Endpoints/EventEndpoints.cs
> +        private async Task<Ok<List<TicketsFromEventAndSectionDto>>> GetSeatsOfSectionOfEvent(int event_id, int section_id, IEventRepository repo)
Yeah, I just copy pasted the paths from the home tasks so that's why they look like that

2024-10-20 15:48 UTC, IuriiSokolov commented on TicketingSystem.ApiService/Repositories/EventRepository/EventRepository.cs
> +            var result = (from sec in _context.Sections
Fixed

2024-10-20 15:49 UTC, IuriiSokolov commented on TicketingSystem.ApiService/Repositories/CartRepository/CartRepository.cs
> +        public async Task<(Cart?, float TotalPriceUsd)> AddTicketToCartAsync(Guid cartId, int eventId, int seatId)
Separated services from repos

2024-10-20 15:49 UTC, IuriiSokolov commented on TicketingSystem.ApiService/Repositories/CartRepository/CartRepository.cs
> +            if (ticket == null)
Yeah, I'm trying to return Task<Results<>> in the endpoints

2024-10-21 08:32 UTC, olegbaslak approved these changes

2024-10-21 08:39 UTC, olegbaslak commented on TicketingSystem.ApiService/Repositories/CartRepository/CartRepository.cs
> +            if (ticket == null)
Results I'm talking about are not from `Microsoft.AspNetCore.Http` package. Take a look at the content of the URL in my message.

2024-10-21 10:44 UTC, merged